Repository chit-a-chat/FE, pull requests merged in 2024-09, with the labels that each got.

#21 [feautre] Select 컴포넌트 추가
  src/shared/ui/Select/Select.tsx
  src/shared/ui/Select/component/MenuItem/MenuItem.tsx
  src/shared/ui/Select/component/MenuList/MenuList.tsx
  src/shared/ui/index.ts
Labels: 기능 추가

#17 [feature] push notification 컴포넌트 구현
  src/shared/type/index.ts
  src/shared/type/themeType.ts
  src/shared/ui/components/flexDiv.ts
  src/shared/ui/index.ts
  src/shared/ui/theme/emotion.d.ts
  src/shared/ui/theme/theme.ts
  src/widgets/components/index.ts
  src/widgets/components/ui/icons.tsx
  src/widgets/components/ui/pushNotification.tsx
Labels: 기능 추가, 도움 요청

#23 [refactor] i18n 타입 정의 및 폴더 구조 변경
  src/features/i18n/en.ts
  src/features/i18n/en/common.ts
  src/features/i18n/en/en.translation.ts
  src/features/i18n/en/home.ts
  src/features/i18n/enExample.ts
  src/features/i18n/i18n.d.ts
  src/features/i18n/index.ts
  src/features/i18n/ko.ts
  src/features/i18n/ko/common.ts
  src/features/i18n/ko/home.ts
  src/features/i18n/ko/ko.translation.ts
  src/features/i18n/koExample.ts
Labels: 기능 수정

#24 [feat] IBM Plex Sans KR이 영어도 지원하도록 수정
  index.css
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-100.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-100.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-200.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-200.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-300.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-300.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-500.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-500.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-600.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-600.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-700.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-700.woff2
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-regular.ttf
  public/fonts/ibm-plex-sans-kr-v10-korean_latin-regular.woff2
Labels: 기능 추가

#25 [chore] 임포트 정리
  src/app/index.tsx
  src/app/router/AppRouter.tsx
  src/shared/routing/index.ts
  src/shared/ui/index.ts
Labels: 기능 수정

#26 [feat] 버튼 컴포넌트 사이즈 추가
  src/shared/ui/theme/theme.ts
  src/widgets/components/ui/button.tsx
Labels: 기능 수정

#30 [bugfix] 타입 안맞는 오류 수정
  src/shared/ui/theme/theme.ts
Labels: 버그

#29 [feat] Text 컴포넌트
  src/shared/ui/Text/Text.tsx
  src/shared/ui/index.ts
Labels: 기능 추가
